import type { Severity } from "@/lib/types";

// Realistic vulnerability templates used by connector demo simulation.
// When a connector is configured with real credentials its adapter maps the
// vendor payload into the same Finding shape instead of drawing from here.
export type VulnTemplate = {
  cve: string;
  title: string;
  severity: Severity;
  cvss: number;
  epss: number;
  category: string;
  description: string;
  remediation: string;
  exploitAvailable: boolean;
};

export const VULN_CATALOG: VulnTemplate[] = [
  {
    cve: "CVE-2024-3400",
    title: "PAN-OS GlobalProtect Command Injection",
    severity: "Critical",
    cvss: 10.0,
    epss: 0.96,
    category: "Network Device",
    description:
      "A command injection vulnerability in the GlobalProtect feature of Palo Alto Networks PAN-OS allows an unauthenticated attacker to execute arbitrary code with root privileges on the firewall.",
    remediation: "Upgrade PAN-OS to a fixed release and apply vendor threat prevention signatures.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2023-4966",
    title: "Citrix NetScaler ADC Session Token Leak (Citrix Bleed)",
    severity: "Critical",
    cvss: 9.4,
    epss: 0.94,
    category: "Remote Access",
    description:
      "Sensitive information disclosure in NetScaler ADC and NetScaler Gateway when configured as a Gateway or AAA virtual server allows session token hijacking.",
    remediation: "Upgrade to a fixed NetScaler build and kill all active/persistent sessions after patching.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2024-21762",
    title: "FortiOS SSL VPN Out-of-Bounds Write RCE",
    severity: "Critical",
    cvss: 9.8,
    epss: 0.91,
    category: "Remote Access",
    description:
      "An out-of-bounds write vulnerability in FortiOS SSL VPN allows a remote unauthenticated attacker to execute arbitrary code via specially crafted HTTP requests.",
    remediation: "Upgrade FortiOS to a fixed version or disable SSL VPN as a temporary workaround.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2021-44228",
    title: "Apache Log4j2 JNDI Remote Code Execution (Log4Shell)",
    severity: "Critical",
    cvss: 10.0,
    epss: 0.97,
    category: "Application Library",
    description:
      "JNDI features in Apache Log4j2 do not protect against attacker-controlled LDAP endpoints, allowing unauthenticated remote code execution via logged data.",
    remediation: "Upgrade log4j-core to 2.17.1 or later; remove the JndiLookup class from legacy deployments.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2024-1709",
    title: "ConnectWise ScreenConnect Authentication Bypass",
    severity: "Critical",
    cvss: 10.0,
    epss: 0.95,
    category: "Remote Access",
    description:
      "An authentication bypass using an alternate path in ScreenConnect 23.9.7 and prior allows creation of admin accounts and full server takeover.",
    remediation: "Upgrade ScreenConnect to 23.9.8 or later immediately and audit for rogue admin users.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2023-34362",
    title: "MOVEit Transfer SQL Injection",
    severity: "Critical",
    cvss: 9.8,
    epss: 0.94,
    category: "File Transfer",
    description:
      "A SQL injection vulnerability in the MOVEit Transfer web application allows an unauthenticated attacker to gain access to the underlying database and deploy webshells.",
    remediation: "Apply the vendor patch, review for LEMURLOOT webshells, and rotate service credentials.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2024-6387",
    title: "OpenSSH regreSSHion Signal Handler Race Condition",
    severity: "High",
    cvss: 8.1,
    epss: 0.62,
    category: "Operating System",
    description:
      "A signal handler race condition in OpenSSH's server (sshd) on glibc-based Linux systems may allow unauthenticated remote code execution as root.",
    remediation: "Update OpenSSH to 9.8p1 or later, or set LoginGraceTime to 0 as a mitigation.",
    exploitAvailable: false,
  },
  {
    cve: "CVE-2023-23397",
    title: "Microsoft Outlook Elevation of Privilege (NTLM Leak)",
    severity: "High",
    cvss: 9.8,
    epss: 0.88,
    category: "Endpoint",
    description:
      "A crafted calendar invite can force Outlook to leak Net-NTLMv2 hashes to an attacker-controlled server with no user interaction.",
    remediation: "Apply the March 2023 Outlook security update and block outbound SMB (445/tcp) at the perimeter.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2024-26169",
    title: "Windows Error Reporting Service Elevation of Privilege",
    severity: "High",
    cvss: 7.8,
    epss: 0.55,
    category: "Endpoint",
    description:
      "An improper privilege management flaw in the Windows Error Reporting Service allows a local attacker to gain SYSTEM privileges; exploited by ransomware operators.",
    remediation: "Apply the March 2024 cumulative Windows update.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2023-38831",
    title: "WinRAR Archive Spoofing Code Execution",
    severity: "High",
    cvss: 7.8,
    epss: 0.83,
    category: "Endpoint",
    description:
      "WinRAR before 6.23 executes attacker code when a user opens a benign-looking file inside a crafted ZIP archive; widely used in phishing campaigns.",
    remediation: "Update WinRAR to 6.23 or later across the fleet.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2022-22965",
    title: "Spring Framework RCE (Spring4Shell)",
    severity: "High",
    cvss: 9.8,
    epss: 0.89,
    category: "Application Library",
    description:
      "A Spring MVC application running on JDK 9+ with WAR deployment on Tomcat is vulnerable to remote code execution via data binding.",
    remediation: "Upgrade Spring Framework to 5.3.18+ / 5.2.20+ and redeploy affected applications.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2023-44487",
    title: "HTTP/2 Rapid Reset Denial of Service",
    severity: "High",
    cvss: 7.5,
    epss: 0.71,
    category: "Web Server",
    description:
      "The HTTP/2 protocol allows request cancellation floods (rapid reset) that exhaust server resources, enabling large-scale denial of service.",
    remediation: "Patch web servers and load balancers to versions with rapid-reset mitigations; enable rate limiting.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2024-23897",
    title: "Jenkins CLI Arbitrary File Read",
    severity: "High",
    cvss: 9.8,
    epss: 0.87,
    category: "CI/CD",
    description:
      "The args4j command parser in Jenkins allows unauthenticated attackers to read arbitrary files on the controller via the built-in CLI, leading to credential theft and RCE chains.",
    remediation: "Upgrade Jenkins to 2.442 / LTS 2.426.3 or later, or disable CLI access.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2021-34473",
    title: "Microsoft Exchange ProxyShell Pre-Auth Path Confusion",
    severity: "High",
    cvss: 9.8,
    epss: 0.92,
    category: "Mail Server",
    description:
      "Path confusion in Exchange's Autodiscover service allows pre-authenticated access that chains to mailbox takeover and remote code execution.",
    remediation: "Apply the July 2021 Exchange security updates and check for dropped webshells.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2019-0708",
    title: "Remote Desktop Services RCE (BlueKeep)",
    severity: "High",
    cvss: 9.8,
    epss: 0.90,
    category: "Operating System",
    description:
      "A use-after-free in Remote Desktop Services on legacy Windows allows unauthenticated remote code execution; wormable.",
    remediation: "Patch or decommission legacy Windows hosts; require NLA and restrict RDP exposure.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2023-27997",
    title: "FortiGate SSL VPN Heap Overflow (XORtigate)",
    severity: "High",
    cvss: 9.8,
    epss: 0.68,
    category: "Remote Access",
    description:
      "A heap-based buffer overflow in FortiOS SSL VPN pre-authentication allows remote code execution on the appliance.",
    remediation: "Upgrade FortiOS; if SSL VPN is unused, disable the portal entirely.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2024-4577",
    title: "PHP-CGI Argument Injection on Windows",
    severity: "High",
    cvss: 9.8,
    epss: 0.86,
    category: "Web Server",
    description:
      "A Best-Fit character conversion flaw lets attackers smuggle arguments to PHP-CGI on Windows, achieving remote code execution on XAMPP-style deployments.",
    remediation: "Upgrade PHP to 8.3.8/8.2.20/8.1.29 or migrate off CGI mode.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2022-30190",
    title: "MSDT Follina Remote Code Execution",
    severity: "High",
    cvss: 7.8,
    epss: 0.85,
    category: "Endpoint",
    description:
      "The Microsoft Support Diagnostic Tool can be invoked via crafted Office documents to run arbitrary PowerShell without macros.",
    remediation: "Apply the June 2022 Windows update; remove the ms-msdt protocol handler on unpatched hosts.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2023-20198",
    title: "Cisco IOS XE Web UI Privilege Escalation",
    severity: "Critical",
    cvss: 10.0,
    epss: 0.93,
    category: "Network Device",
    description:
      "An unauthenticated attacker can create a privilege-15 account through the IOS XE web UI, gaining full control of the device.",
    remediation: "Upgrade IOS XE and disable the HTTP/HTTPS server feature on internet-facing devices.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2016-2183",
    title: "SSL/TLS 64-bit Block Cipher SWEET32",
    severity: "Medium",
    cvss: 7.5,
    epss: 0.12,
    category: "Cryptography",
    description:
      "Use of 3DES cipher suites in long-lived TLS sessions allows birthday attacks that can recover session data.",
    remediation: "Disable 3DES/DES cipher suites and prefer AES-GCM suites in TLS configuration.",
    exploitAvailable: false,
  },
  {
    cve: "CVE-2020-1472",
    title: "Netlogon Elevation of Privilege (Zerologon)",
    severity: "Critical",
    cvss: 10.0,
    epss: 0.92,
    category: "Directory Services",
    description:
      "A cryptographic flaw in the Netlogon Remote Protocol allows an attacker with network access to a domain controller to reset its machine account and take over the domain.",
    remediation: "Apply the August 2020 updates and enable Netlogon secure channel enforcement.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2017-0144",
    title: "SMBv1 Remote Code Execution (EternalBlue)",
    severity: "High",
    cvss: 8.1,
    epss: 0.94,
    category: "Operating System",
    description:
      "The SMBv1 server improperly handles crafted packets, allowing remote code execution; used by WannaCry and NotPetya.",
    remediation: "Apply MS17-010 and disable SMBv1 across the estate.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2023-48795",
    title: "SSH Prefix Truncation (Terrapin)",
    severity: "Medium",
    cvss: 5.9,
    epss: 0.18,
    category: "Cryptography",
    description:
      "The SSH transport protocol allows a man-in-the-middle to strip initial handshake messages, downgrading connection security when ChaCha20-Poly1305 or CBC-EtM is negotiated.",
    remediation: "Update SSH clients and servers to versions supporting strict key exchange.",
    exploitAvailable: false,
  },
  {
    cve: "CVE-2021-40438",
    title: "Apache HTTP Server mod_proxy SSRF",
    severity: "Medium",
    cvss: 9.0,
    epss: 0.72,
    category: "Web Server",
    description:
      "A crafted request uri-path can cause mod_proxy to forward the request to an origin server chosen by the remote user.",
    remediation: "Upgrade Apache HTTP Server to 2.4.49 or later.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2022-1388",
    title: "F5 BIG-IP iControl REST Authentication Bypass",
    severity: "Critical",
    cvss: 9.8,
    epss: 0.93,
    category: "Network Device",
    description:
      "Undisclosed requests may bypass iControl REST authentication, allowing attackers to execute arbitrary system commands on BIG-IP appliances.",
    remediation: "Upgrade BIG-IP or block iControl REST access via self IPs and management interface ACLs.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2023-22515",
    title: "Confluence Data Center Broken Access Control",
    severity: "Critical",
    cvss: 10.0,
    epss: 0.90,
    category: "Collaboration",
    description:
      "Remote attackers can create unauthorized administrator accounts in Confluence Data Center and Server instances via the setup endpoints.",
    remediation: "Upgrade Confluence and audit for unexpected admin users and installed apps.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2024-27198",
    title: "JetBrains TeamCity Authentication Bypass",
    severity: "Critical",
    cvss: 9.8,
    epss: 0.89,
    category: "CI/CD",
    description:
      "An alternative path issue in TeamCity allows a remote unauthenticated attacker to take full administrative control of the server.",
    remediation: "Upgrade TeamCity to 2023.11.4 or later.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2018-13379",
    title: "FortiOS SSL VPN Path Traversal Credential Disclosure",
    severity: "High",
    cvss: 9.8,
    epss: 0.91,
    category: "Remote Access",
    description:
      "A path traversal in the FortiOS SSL VPN web portal allows unauthenticated download of system files including plaintext VPN credentials.",
    remediation: "Upgrade FortiOS and force a credential reset for all SSL VPN users.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2015-4000",
    title: "TLS DHE Export Cipher Downgrade (Logjam)",
    severity: "Low",
    cvss: 3.7,
    epss: 0.05,
    category: "Cryptography",
    description:
      "TLS servers supporting export-grade Diffie-Hellman allow man-in-the-middle downgrade of connections to 512-bit keys.",
    remediation: "Disable export cipher suites and use 2048-bit or larger DH groups.",
    exploitAvailable: false,
  },
  {
    cve: "CVE-2023-46805",
    title: "Ivanti Connect Secure Authentication Bypass",
    severity: "High",
    cvss: 8.2,
    epss: 0.90,
    category: "Remote Access",
    description:
      "An authentication bypass in the web component of Ivanti Connect Secure allows access to restricted resources; chained with CVE-2024-21887 for RCE.",
    remediation: "Apply Ivanti patches, run the external integrity checker, and rotate all secrets on affected appliances.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2024-47575",
    title: "FortiManager Missing Authentication (FortiJump)",
    severity: "Critical",
    cvss: 9.8,
    epss: 0.82,
    category: "Network Device",
    description:
      "Missing authentication for a critical function in FortiManager fgfmd allows a remote attacker to execute arbitrary code via crafted requests.",
    remediation: "Upgrade FortiManager and restrict FGFM access to known device IPs.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2022-26134",
    title: "Confluence OGNL Injection RCE",
    severity: "Critical",
    cvss: 9.8,
    epss: 0.94,
    category: "Collaboration",
    description:
      "An OGNL injection vulnerability allows an unauthenticated attacker to execute arbitrary code on Confluence Server and Data Center.",
    remediation: "Upgrade Confluence to a fixed version and review access logs for exploitation.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2014-3566",
    title: "SSLv3 Padding Oracle (POODLE)",
    severity: "Low",
    cvss: 3.4,
    epss: 0.04,
    category: "Cryptography",
    description:
      "The SSL 3.0 protocol uses nondeterministic CBC padding, allowing man-in-the-middle attackers to decrypt session data.",
    remediation: "Disable SSLv3 on all services; require TLS 1.2 or later.",
    exploitAvailable: false,
  },
  {
    cve: "CVE-2024-38063",
    title: "Windows TCP/IP IPv6 Remote Code Execution",
    severity: "Critical",
    cvss: 9.8,
    epss: 0.58,
    category: "Operating System",
    description:
      "An integer underflow in the Windows TCP/IP stack allows unauthenticated remote code execution via crafted IPv6 packets.",
    remediation: "Apply the August 2024 cumulative update; disable IPv6 only as a last-resort mitigation.",
    exploitAvailable: false,
  },
  {
    cve: "CVE-2016-0800",
    title: "SSLv2 Cross-Protocol Attack (DROWN)",
    severity: "Medium",
    cvss: 5.9,
    epss: 0.09,
    category: "Cryptography",
    description:
      "Servers supporting SSLv2 allow attackers to decrypt TLS sessions that share the same RSA key via a cross-protocol Bleichenbacher attack.",
    remediation: "Disable SSLv2 everywhere and ensure private keys are not shared with legacy services.",
    exploitAvailable: false,
  },
  {
    cve: "CVE-2024-20353",
    title: "Cisco ASA/FTD Web Services Denial of Service",
    severity: "High",
    cvss: 8.6,
    epss: 0.34,
    category: "Network Device",
    description:
      "An infinite-loop condition in the management web server of Cisco ASA and FTD allows a remote attacker to force a device reload; part of ArcaneDoor activity.",
    remediation: "Upgrade ASA/FTD software per Cisco advisory cisco-sa-asaftd-websrvs-dos-X8gNucD2.",
    exploitAvailable: false,
  },
  {
    cve: "CVE-2019-19781",
    title: "Citrix ADC Directory Traversal RCE (Shitrix)",
    severity: "Critical",
    cvss: 9.8,
    epss: 0.95,
    category: "Remote Access",
    description:
      "A directory traversal in Citrix ADC and Gateway allows unauthenticated remote code execution via the VPN vserver.",
    remediation: "Apply Citrix fixes and check for persistence in /netscaler/portal/templates.",
    exploitAvailable: true,
  },
  {
    cve: "CVE-2005-4900",
    title: "SHA-1 Certificate Signature Weakness",
    severity: "Info",
    cvss: 0.0,
    epss: 0.01,
    category: "Cryptography",
    description:
      "Service presents a certificate chain signed with SHA-1, which is vulnerable to collision attacks and rejected by modern clients.",
    remediation: "Reissue certificates with SHA-256 or stronger signatures.",
    exploitAvailable: false,
  },
  {
    cve: "N/A-BANNER",
    title: "Service Banner Discloses Software Version",
    severity: "Info",
    cvss: 0.0,
    epss: 0.0,
    category: "Information Disclosure",
    description:
      "The service banner reveals exact software name and version, easing targeted exploitation by attackers.",
    remediation: "Suppress or genericize service banners where operationally possible.",
    exploitAvailable: false,
  },
  {
    cve: "N/A-SELFSIGNED",
    title: "Self-Signed TLS Certificate In Use",
    severity: "Low",
    cvss: 3.7,
    epss: 0.02,
    category: "Cryptography",
    description:
      "The service presents a self-signed certificate, training users to ignore trust warnings and enabling man-in-the-middle interception.",
    remediation: "Deploy certificates issued by the internal PKI or a trusted public CA.",
    exploitAvailable: false,
  },
];

export const DEMO_ASSETS = [
  "dc01.gmi.local",
  "dc02.gmi.local",
  "fw-edge-01.gmi.local",
  "fw-edge-02.gmi.local",
  "vpn.gmi.com",
  "mail.gmi.com",
  "web-prod-01.gmi.com",
  "web-prod-02.gmi.com",
  "app-erp-01.gmi.local",
  "sql-prod-01.gmi.local",
  "sql-prod-02.gmi.local",
  "jump-01.gmi.local",
  "ci-build-01.gmi.local",
  "wiki.gmi.local",
  "files.gmi.local",
  "ws-fin-114.gmi.local",
  "ws-eng-207.gmi.local",
  "ws-ops-052.gmi.local",
  "esxi-01.gmi.local",
  "nas-01.gmi.local",
];

export const DEMO_PORTS = [
  "443/tcp",
  "22/tcp",
  "3389/tcp",
  "445/tcp",
  "8443/tcp",
  "80/tcp",
  "1433/tcp",
  "25/tcp",
  "8080/tcp",
  "N/A",
];
